### ISSUE TITLE
Details in PDF-report is empty

### ISSUE THREAD

**Issue by prince74igor** [adedayo/checkmate#2]
Hi.

The software is excellent, but when I tried to generate PDF-file I can't see details about secrets.
I have tried to change asciidocctor-pdf gem and checkmate versions, use it in linux and macOS - nothing.
What should I do?
Please see [the report ](https://drive.google.com/drive/folders/1nYxbhQ0GdRy1GjimnVN0gKy3zbhETXfw?usp=share_link)

**Comment by adedayo** [comment]
Hello @prince74igor ,

 Thank you for your feedback. I shall investigate this and get back to you shortly. Can you please let me know what version of asciidoctor-pdf you are using?

Cheers.

**Comment by adedayo** [comment]
The issue has now been fixed in the latest release v0.8.3.

Thank you for raising this.

Kind regards,
Dayo

**Comment by prince74igor** [comment]
@adedayo, I'm late, sorry..
I have tried almost every existing version of asciidoctor-pdf.

I checked - it works! You are amazing!
Special thanks for the quick response.

**Comment by adedayo** [comment]
Thank you so much for the feedback @prince74igor!
